--- 
- 
  become: true
  gather_facts: true
  hosts: all
  remote_user: root         # Update username for remote server
  vars:
    tomcat_ver: 9.0.30                          # Tomcat version to install
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: Str0ngManagerP@ssw3rd      # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: Str0ngAdminP@ssw3rd          # UI admin password
  roles:
    - tomcat
  tasks: 
    - 
      yum: 
        name: 
          - git
          - wget
          - curl
          - vim
          - nano
    - 
      include: Setup.yml
      name: "Running Setup"
